# Generated by Django 4.0.3 on 2022-03-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('staffer', 'Staffer'), ('manager', 'Manager'), ('deputy director', 'Deputy Director'), ('director', 'Director')], max_length=20)),
            ],
        ),
    ]
