# Generated by Django 4.0.3 on 2022-03-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_approval_bidding_case_domain_team_userdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='folder_link',
            field=models.URLField(default=None, max_length=2000),
            preserve_default=False,
        ),
    ]
