# Generated by Django 4.0.3 on 2022-03-03 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0003_case_folder_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name_plural': 'users details'},
        ),
        migrations.AlterField(
            model_name='approval',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='supported2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='supported_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='supporter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_supporter1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approval',
            name='supporter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_supporter2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approval',
            name='vetted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='vetter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_vetter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='supported2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='supported_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='supporter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_supporter1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='supporter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_supporter2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='vetted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='vetter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_vetter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='bidding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.bidding'),
        ),
        migrations.AlterField(
            model_name='case',
            name='current_status',
            field=models.CharField(choices=[('planning', 'Planning'), ('bidding', 'Bidding'), ('approval', 'Approval'), ('contracting', 'Contracting'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='current_step',
            field=models.CharField(choices=[('drafting', 'Drafting'), ('vetting', 'Vetting'), ('clearance1', 'Clearance 1'), ('clearance2', 'Clearance 2'), ('pending approval', 'Pending Approval'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='next_step',
            field=models.CharField(blank=True, choices=[('drafting', 'Drafting'), ('vetting', 'Vetting'), ('clearance1', 'Clearance 1'), ('clearance2', 'Clearance 2'), ('pending approval', 'Pending Approval'), ('completed', 'Completed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='next_step_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_step_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.planning'),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='supported2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='supported_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='supporter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracting_supporter1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='supporter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracting_supporter2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='vetted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='vetter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracting_vetter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planning',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='supported2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='supported_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='supporter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planning_supporter1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planning',
            name='supporter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planning_supporter2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planning',
            name='vetted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='vetter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planning_vetter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='supporter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_supporter1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='supporter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_supporter2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='vetter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_vetter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.team'),
        ),
    ]
