# Generated by Django 4.0.3 on 2022-03-07 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0008_alter_userdetails_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='approval',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.approval'),
        ),
        migrations.AlterField(
            model_name='case',
            name='bidding',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.bidding'),
        ),
        migrations.AlterField(
            model_name='case',
            name='contracting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.contracting'),
        ),
        migrations.AlterField(
            model_name='case',
            name='planning',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.planning'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.appointment'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.domain'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
