# Generated by Django 4.0.3 on 2022-03-08 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_case_approval_alter_case_bidding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='current_step_due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
