# Generated by Django 4.0.3 on 2022-03-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_case_current_step_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='current_step_due_date',
            new_name='current_status_due_date',
        ),
    ]
