# Generated by Django 4.0.3 on 2022-03-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregister', '0002_step_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
