# Generated by Django 4.0.3 on 2022-03-08 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pregister', '0004_alter_step_res_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pregister.case'),
        ),
    ]
