# Generated by Django 4.0.3 on 2022-03-08 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pregister', '0005_alter_step_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pregister.case'),
        ),
    ]
