# Generated by Django 4.0.3 on 2022-03-09 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pregister', '0006_alter_step_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='stage_deadline',
        ),
        migrations.RemoveField(
            model_name='step',
            name='type',
        ),
        migrations.AddField(
            model_name='case',
            name='approval_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='bidding_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='contracting_deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='current_res_party',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='project_res_party', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='planning_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='purchase_type',
            field=models.CharField(choices=[('O', 'O'), ('L', 'L'), ('D', 'D'), ('V', 'V'), ('N', 'N')], default='O', max_length=5),
            preserve_default=False,
        ),
    ]
