# Generated by Django 4.0.3 on 2022-03-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregister', '0007_remove_step_stage_deadline_remove_step_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='approval_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='contracting_type',
            field=models.CharField(choices=[('C', 'C'), ('D', 'D'), ('E', 'E'), ('M', 'M')], default='E', max_length=5),
            preserve_default=False,
        ),
    ]
