# Generated by Django 4.0.3 on 2022-03-09 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pregister', '0008_case_approval_type_case_contracting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
