# Generated by Django 4.0.3 on 2022-03-09 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pregister', '0009_step_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['created_date']},
        ),
    ]
