# Generated by Django 4.0.3 on 2022-03-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregister', '0010_alter_step_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='approval_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='need_by_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(choices=[('services', 'Services'), ('infocomm tech', 'Infocomm Tech'), ('general goods', 'General Goods'), ('admin', 'Admin')], max_length=20),
        ),
    ]
