# Generated by Django 4.0.3 on 2022-03-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregister', '0012_alter_step_options_alter_step_stage_alter_step_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterField(
            model_name='step',
            name='stage',
            field=models.CharField(choices=[('planning', 'Planning'), ('bidding', 'Bidding'), ('approval', 'Approval'), ('contracting', 'Contracting')], max_length=20),
        ),
        migrations.AlterField(
            model_name='step',
            name='step',
            field=models.CharField(choices=[('drafting', 'Drafting'), ('vetting', 'Vetting'), ('support1', 'Support1'), ('support2', 'Support2'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
