# Generated by Django 4.0.3 on 2022-03-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregister', '0013_alter_step_options_alter_step_stage_alter_step_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['case', 'stage', 'step']},
        ),
        migrations.AlterField(
            model_name='step',
            name='stage',
            field=models.CharField(choices=[('1. planning', '1. Planning'), ('2. bidding', '2. Bidding'), ('3. approval', '3. Approval'), ('4. contracting', '4. Contracting')], max_length=20),
        ),
        migrations.AlterField(
            model_name='step',
            name='step',
            field=models.CharField(choices=[('1. drafting', '1. Drafting'), ('2. vetting', '2. Vetting'), ('3. support1', '3. Support1'), ('4. support2', '4. Support2'), ('5. completed', '5. Completed'), ('6. cancelled', '6. Cancelled')], max_length=20),
        ),
    ]
